//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testt
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// .
    /// </summary>
    // *** Start programmer edit section *** (AggregationClass CustomAttributes)

    // *** End programmer edit section *** (AggregationClass CustomAttributes)
    [AutoAltered()]
    [Caption("")]
    [View("AggregationD", new string[] {
            "AggregationAtr as \'AggregationAtr\'"})]
    [View("AggregationE", new string[] {
            "AggregationAtr as \'AggregationAtr\'"})]
    [View("AggregationL", new string[] {
            "AggregationAtr as \'AggregationAtr\'"})]
    public class AggregationClass : ICSSoft.STORMNET.DataObject
    {

        private string fAggregationAtr;

        private Testt.ClassTest fClassTest;

        // *** Start programmer edit section *** (AggregationClass CustomMembers)

        // *** End programmer edit section *** (AggregationClass CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (AggregationClass.AggregationAtr CustomAttributes)

        // *** End programmer edit section *** (AggregationClass.AggregationAtr CustomAttributes)
        public virtual string AggregationAtr
        {
            get
            {
                // *** Start programmer edit section *** (AggregationClass.AggregationAtr Get start)

                // *** End programmer edit section *** (AggregationClass.AggregationAtr Get start)
                string result = this.fAggregationAtr;
                // *** Start programmer edit section *** (AggregationClass.AggregationAtr Get end)

                // *** End programmer edit section *** (AggregationClass.AggregationAtr Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (AggregationClass.AggregationAtr Set start)

                // *** End programmer edit section *** (AggregationClass.AggregationAtr Set start)
                this.fAggregationAtr = value;
                // *** Start programmer edit section *** (AggregationClass.AggregationAtr Set end)

                // *** End programmer edit section *** (AggregationClass.AggregationAtr Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (AggregationClass.ClassTest CustomAttributes)

        // *** End programmer edit section *** (AggregationClass.ClassTest CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ClassTest"})]
        public virtual Testt.ClassTest ClassTest
        {
            get
            {
                // *** Start programmer edit section *** (AggregationClass.ClassTest Get start)

                // *** End programmer edit section *** (AggregationClass.ClassTest Get start)
                Testt.ClassTest result = this.fClassTest;
                // *** Start programmer edit section *** (AggregationClass.ClassTest Get end)

                // *** End programmer edit section *** (AggregationClass.ClassTest Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (AggregationClass.ClassTest Set start)

                // *** End programmer edit section *** (AggregationClass.ClassTest Set start)
                this.fClassTest = value;
                // *** Start programmer edit section *** (AggregationClass.ClassTest Set end)

                // *** End programmer edit section *** (AggregationClass.ClassTest Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "AggregationD" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AggregationD
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AggregationD", typeof(Testt.AggregationClass));
                }
            }

            /// <summary>
            /// "AggregationE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AggregationE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AggregationE", typeof(Testt.AggregationClass));
                }
            }

            /// <summary>
            /// "AggregationL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AggregationL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AggregationL", typeof(Testt.AggregationClass));
                }
            }
        }

    }

    /// <summary>
    /// Detail array of AggregationClass.
    /// </summary>
    public class DetailArrayOfAggregationClass : ICSSoft.STORMNET.DetailArray
    {
        /// <summary>
        /// Construct detail array.
        /// </summary>
        public DetailArrayOfAggregationClass(Testt.ClassTest fClassTest) :
                base(typeof(AggregationClass), ((ICSSoft.STORMNET.DataObject)(fClassTest)))
        {
        }

        /// <summary>
        /// Returns object with type AggregationClass by index.
        /// </summary>
        public Testt.AggregationClass this[int index]
        {
            get
            {
                return ((Testt.AggregationClass)(this.ItemByIndex(index)));
            }
        }

        /// <summary>
        /// Adds object with type AggregationClass.
        /// </summary>
        public virtual void Add(Testt.AggregationClass dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
