//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testt
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// .
    /// </summary>
    // *** Start programmer edit section *** (AssosiationClass CustomAttributes)

    // *** End programmer edit section *** (AssosiationClass CustomAttributes)
    [AutoAltered()]
    [Caption("")]
    [View("AssosiationE", new string[] {
            "AssosiationName"})]
    [View("AssosiationL", new string[] {
            "AssosiationName"})]
    public class AssosiationClass : ICSSoft.STORMNET.DataObject
    {

        private string fAssosiationName;

        // *** Start programmer edit section *** (AssosiationClass CustomMembers)

        // *** End programmer edit section *** (AssosiationClass CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (AssosiationClass.AssosiationName CustomAttributes)

        // *** End programmer edit section *** (AssosiationClass.AssosiationName CustomAttributes)
        public virtual string AssosiationName
        {
            get
            {
                // *** Start programmer edit section *** (AssosiationClass.AssosiationName Get start)

                // *** End programmer edit section *** (AssosiationClass.AssosiationName Get start)
                string result = this.fAssosiationName;
                // *** Start programmer edit section *** (AssosiationClass.AssosiationName Get end)

                // *** End programmer edit section *** (AssosiationClass.AssosiationName Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (AssosiationClass.AssosiationName Set start)

                // *** End programmer edit section *** (AssosiationClass.AssosiationName Set start)
                this.fAssosiationName = value;
                // *** Start programmer edit section *** (AssosiationClass.AssosiationName Set end)

                // *** End programmer edit section *** (AssosiationClass.AssosiationName Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "AssosiationE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AssosiationE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AssosiationE", typeof(Testt.AssosiationClass));
                }
            }

            /// <summary>
            /// "AssosiationL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View AssosiationL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("AssosiationL", typeof(Testt.AssosiationClass));
                }
            }
        }

    }
}
