//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testt
{
    using System;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// .
    /// </summary>
    // *** Start programmer edit section *** (BusinessClass CustomAttributes)

    // *** End programmer edit section *** (BusinessClass CustomAttributes)
    [BusinessServer("Testt.BusinessClassBS, Testt.BusinessServers", ICSSoft.STORMNET.Business.DataServiceObjectEvents.OnAllEvents)]
    [AutoAltered()]
    [Caption("")]
    public class BusinessClass : ICSSoft.STORMNET.DataObject
    {

        private string fbstest;

        // *** Start programmer edit section *** (BusinessClass CustomMembers)

        // *** End programmer edit section *** (BusinessClass CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (BusinessClass.bstest CustomAttributes)

        // *** End programmer edit section *** (BusinessClass.bstest CustomAttributes)
        public virtual string bstest
        {
            get
            {
                // *** Start programmer edit section *** (BusinessClass.bstest Get start)

                // *** End programmer edit section *** (BusinessClass.bstest Get start)
                string result = this.fbstest;
                // *** Start programmer edit section *** (BusinessClass.bstest Get end)

                // *** End programmer edit section *** (BusinessClass.bstest Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (BusinessClass.bstest Set start)

                // *** End programmer edit section *** (BusinessClass.bstest Set start)
                this.fbstest = value;
                // *** Start programmer edit section *** (BusinessClass.bstest Set end)

                // *** End programmer edit section *** (BusinessClass.bstest Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
        }

    }
}
