//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testt
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// .
    /// </summary>
    // *** Start programmer edit section *** (ClassTest CustomAttributes)

    // *** End programmer edit section *** (ClassTest CustomAttributes)
    [AutoAltered()]
    [Caption("")]
    [View("ClassTestE", new string[] {
            "Address as \'Address\'",
            "Name as \'Name\'",
            "AssosiationClass as \'AssosiationClass\'"})]
    [AssociatedDetailViewAttribute("ClassTestE", "AggregationClass", "AggregationD", true, "", "AggregationClass", true, new string[] {
            ""})]
    [View("ClassTestL", new string[] {
            "Address as \'Address\'",
            "Name as \'Name\'"})]
    public class ClassTest : ICSSoft.STORMNET.DataObject
    {

        private string fAddress;

        private ClassEnum fName;

        private Testt.AssosiationClass fAssosiationClass;

        private Testt.DetailArrayOfAggregationClass fAggregationClass;

        // *** Start programmer edit section *** (ClassTest CustomMembers)

        // *** End programmer edit section *** (ClassTest CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (ClassTest.Address CustomAttributes)

        // *** End programmer edit section *** (ClassTest.Address CustomAttributes)
        public virtual string Address
        {
            get
            {
                // *** Start programmer edit section *** (ClassTest.Address Get start)

                // *** End programmer edit section *** (ClassTest.Address Get start)
                string result = this.fAddress;
                // *** Start programmer edit section *** (ClassTest.Address Get end)

                // *** End programmer edit section *** (ClassTest.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ClassTest.Address Set start)

                // *** End programmer edit section *** (ClassTest.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (ClassTest.Address Set end)

                // *** End programmer edit section *** (ClassTest.Address Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (ClassTest.Name CustomAttributes)

        // *** End programmer edit section *** (ClassTest.Name CustomAttributes)
        public virtual ClassEnum Name
        {
            get
            {
                // *** Start programmer edit section *** (ClassTest.Name Get start)

                // *** End programmer edit section *** (ClassTest.Name Get start)
                ClassEnum result = this.fName;
                // *** Start programmer edit section *** (ClassTest.Name Get end)

                // *** End programmer edit section *** (ClassTest.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ClassTest.Name Set start)

                // *** End programmer edit section *** (ClassTest.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (ClassTest.Name Set end)

                // *** End programmer edit section *** (ClassTest.Name Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (ClassTest.AssosiationClass CustomAttributes)

        // *** End programmer edit section *** (ClassTest.AssosiationClass CustomAttributes)
        [NotNull()]
        [PropertyStorage(new string[] {
                "AssosiationClass"})]
        public virtual Testt.AssosiationClass AssosiationClass
        {
            get
            {
                // *** Start programmer edit section *** (ClassTest.AssosiationClass Get start)

                // *** End programmer edit section *** (ClassTest.AssosiationClass Get start)
                Testt.AssosiationClass result = this.fAssosiationClass;
                // *** Start programmer edit section *** (ClassTest.AssosiationClass Get end)

                // *** End programmer edit section *** (ClassTest.AssosiationClass Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ClassTest.AssosiationClass Set start)

                // *** End programmer edit section *** (ClassTest.AssosiationClass Set start)
                this.fAssosiationClass = value;
                // *** Start programmer edit section *** (ClassTest.AssosiationClass Set end)

                // *** End programmer edit section *** (ClassTest.AssosiationClass Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (ClassTest.AggregationClass CustomAttributes)

        // *** End programmer edit section *** (ClassTest.AggregationClass CustomAttributes)
        [PropertyStorage(new string[] {
                "ClassTest"})]
        public virtual Testt.DetailArrayOfAggregationClass AggregationClass
        {
            get
            {
                // *** Start programmer edit section *** (ClassTest.AggregationClass Get start)

                // *** End programmer edit section *** (ClassTest.AggregationClass Get start)
                if ((this.fAggregationClass == null))
                {
                    this.fAggregationClass = new Testt.DetailArrayOfAggregationClass(this);
                }
                Testt.DetailArrayOfAggregationClass result = this.fAggregationClass;
                // *** Start programmer edit section *** (ClassTest.AggregationClass Get end)

                // *** End programmer edit section *** (ClassTest.AggregationClass Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ClassTest.AggregationClass Set start)

                // *** End programmer edit section *** (ClassTest.AggregationClass Set start)
                this.fAggregationClass = value;
                // *** Start programmer edit section *** (ClassTest.AggregationClass Set end)

                // *** End programmer edit section *** (ClassTest.AggregationClass Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ClassTestE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClassTestE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClassTestE", typeof(Testt.ClassTest));
                }
            }

            /// <summary>
            /// "ClassTestL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClassTestL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClassTestL", typeof(Testt.ClassTest));
                }
            }
        }

    }
}
