//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testt
{
    using System;
    using ICSSoft.STORMNET;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// .
    /// </summary>
    // *** Start programmer edit section *** (ClassTest CustomAttributes)

    // *** End programmer edit section *** (ClassTest CustomAttributes)
    [AutoAltered()]
    [Caption("")]
    [View("ClassTestE", new string[] {
            "Address as \'Address\'",
            "Name as \'Name\'",
            "AssosiationClass as \'AssosiationClass\'"})]
    [AssociatedDetailViewAttribute("ClassTestE", "AggregationClass", "AggregationD", true, "", "AggregationClass", true, new string[] {
            ""})]
    [View("ClassTestL", new string[] {
            "Address as \'Address\'",
            "Name as \'Name\'"})]
    public class ClassTest : ICSSoft.STORMNET.DataObject
    {

        private string fAddress;

        private ClassEnum fName;

        private Testt.AssosiationClass fAssosiationClass;

        private Testt.DetailArrayOfAggregationClass fAggregationClass;

        // *** Start programmer edit section *** (ClassTest CustomMembers)

        // *** End programmer edit section *** (ClassTest CustomMembers)


        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (ClassTest.Address CustomAttributes)

        // *** End programmer edit section *** (ClassTest.Address CustomAttributes)
        public virtual string Address
        {
            get
            {
                // *** Start programmer edit section *** (ClassTest.Address Get start)

                // *** End programmer edit section *** (ClassTest.Address Get start)
                string result = this.fAddress;
                // *** Start programmer edit section *** (ClassTest.Address Get end)

                // *** End programmer edit section *** (ClassTest.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ClassTest.Address Set start)

                // *** End programmer edit section *** (ClassTest.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (ClassTest.Address Set end)

                // *** End programmer edit section *** (ClassTest.Address Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (ClassTest.Name CustomAttributes)

        // *** End programmer edit section *** (ClassTest.Name CustomAttributes)
        public virtual ClassEnum Name
        {
            get
            {
                // *** Start programmer edit section *** (ClassTest.Name Get start)

                // *** End programmer edit section *** (ClassTest.Name Get start)
                ClassEnum result = this.fName;
                // *** Start programmer edit section *** (ClassTest.Name Get end)

                // *** End programmer edit section *** (ClassTest.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ClassTest.Name Set start)

                // *** End programmer edit section *** (ClassTest.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (ClassTest.Name Set end)

                // *** End programmer edit section *** (ClassTest.Name Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (ClassTest.AssosiationClass CustomAttributes)

        // *** End programmer edit section *** (ClassTest.AssosiationClass CustomAttributes)
        [NotNull()]
        [PropertyStorage(new string[] {
                "AssosiationClass"})]
        public virtual Testt.AssosiationClass AssosiationClass
        {
            get
            {
                // *** Start programmer edit section *** (ClassTest.AssosiationClass Get start)

                // *** End programmer edit section *** (ClassTest.AssosiationClass Get start)
                Testt.AssosiationClass result = this.fAssosiationClass;
                // *** Start programmer edit section *** (ClassTest.AssosiationClass Get end)

                // *** End programmer edit section *** (ClassTest.AssosiationClass Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ClassTest.AssosiationClass Set start)

                // *** End programmer edit section *** (ClassTest.AssosiationClass Set start)
                this.fAssosiationClass = value;
                // *** Start programmer edit section *** (ClassTest.AssosiationClass Set end)

                // *** End programmer edit section *** (ClassTest.AssosiationClass Set end)
            }
        }

        /// <summary>
        /// .
        /// </summary>
        // *** Start programmer edit section *** (ClassTest.AggregationClass CustomAttributes)

        // *** End programmer edit section *** (ClassTest.AggregationClass CustomAttributes)
        [PropertyStorage(new string[] {
                "ClassTest"})]
        public virtual Testt.DetailArrayOfAggregationClass AggregationClass
        {
            get
            {
                // *** Start programmer edit section *** (ClassTest.AggregationClass Get start)

                // *** End programmer edit section *** (ClassTest.AggregationClass Get start)
                if ((this.fAggregationClass == null))
                {
                    this.fAggregationClass = new Testt.DetailArrayOfAggregationClass(this);
                }
                Testt.DetailArrayOfAggregationClass result = this.fAggregationClass;
                // *** Start programmer edit section *** (ClassTest.AggregationClass Get end)

                // *** End programmer edit section *** (ClassTest.AggregationClass Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ClassTest.AggregationClass Set start)

                // *** End programmer edit section *** (ClassTest.AggregationClass Set start)
                this.fAggregationClass = value;
                // *** Start programmer edit section *** (ClassTest.AggregationClass Set end)

                // *** End programmer edit section *** (ClassTest.AggregationClass Set end)
            }
        }

        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {

            /// <summary>
            /// "ClassTestE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClassTestE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClassTestE", typeof(Testt.ClassTest));
                }
            }

            /// <summary>
            /// "ClassTestL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ClassTestL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ClassTestL", typeof(Testt.ClassTest));
                }
            }
        }

        /// <summary>
        /// Audit class settings.
        /// </summary>
        public class AuditSettings
        {

            /// <summary>
            /// Включён ли аудит для класса.
            /// </summary>
            public static bool AuditEnabled = true;

            /// <summary>
            /// Использовать имя представления для аудита по умолчанию.
            /// </summary>
            public static bool UseDefaultView = false;

            /// <summary>
            /// Включён ли аудит операции чтения.
            /// </summary>
            public static bool SelectAudit = false;

            /// <summary>
            /// Имя представления для аудирования операции чтения.
            /// </summary>
            public static string SelectAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции создания.
            /// </summary>
            public static bool InsertAudit = false;

            /// <summary>
            /// Имя представления для аудирования операции создания.
            /// </summary>
            public static string InsertAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции изменения.
            /// </summary>
            public static bool UpdateAudit = false;

            /// <summary>
            /// Имя представления для аудирования операции изменения.
            /// </summary>
            public static string UpdateAuditViewName = "AuditView";

            /// <summary>
            /// Включён ли аудит операции удаления.
            /// </summary>
            public static bool DeleteAudit = false;

            /// <summary>
            /// Имя представления для аудирования операции удаления.
            /// </summary>
            public static string DeleteAuditViewName = "AuditView";

            /// <summary>
            /// Путь к форме просмотра результатов аудита.
            /// </summary>
            public static string FormUrl = "";

            /// <summary>
            /// Режим записи данных аудита (синхронный или асинхронный).
            /// </summary>
            public static ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode WriteMode = ICSSoft.STORMNET.Business.Audit.Objects.tWriteMode.Synchronous;

            /// <summary>
            /// Максимальная длина сохраняемого значения поля (если 0, то строка обрезаться не будет).
            /// </summary>
            public static int PrunningLength = 0;

            /// <summary>
            /// Показывать ли пользователям в изменениях первичные ключи.
            /// </summary>
            public static bool ShowPrimaryKey = false;

            /// <summary>
            /// Сохранять ли старое значение.
            /// </summary>
            public static bool KeepOldValue = true;

            /// <summary>
            /// Сжимать ли сохраняемые значения.
            /// </summary>
            public static bool Compress = false;

            /// <summary>
            /// Сохранять ли все значения атрибутов, а не только изменяемые.
            /// </summary>
            public static bool KeepAllValues = false;
        }
    }
}
