//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testt
{
    using System.ComponentModel;
    using System.Text.Json.Serialization;
    using ICSSoft.STORMNET;

    /// <summary>
    /// .
    /// </summary>
    [TypeConverter(typeof(CaptionEnumConverter))]
    [JsonConverter(typeof(JsonCaptionEnumConverterFactory))]
    public enum ClassEnum
    {

        [Caption("class1")]
        class1,

        [Caption("class2")]
        class2,

        [Caption("class3")]
        class3,
    }
}
