//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseAggregationClass {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseAggregationClass custom)

  // *** End programmer edit section *** (IBaseAggregationClass custom)
}

export interface IAggregationD extends IBaseAggregationClass {
  aggregationAtr: string;
  // *** Start programmer edit section *** (IAggregationD custom)

  // *** End programmer edit section *** (IAggregationD custom)
}

export interface IAggregationE extends IBaseAggregationClass {
  aggregationAtr: string;
  // *** Start programmer edit section *** (IAggregationE custom)

  // *** End programmer edit section *** (IAggregationE custom)
}

export interface IAggregationL extends IBaseAggregationClass {
  aggregationAtr: string;
  // *** Start programmer edit section *** (IAggregationL custom)

  // *** End programmer edit section *** (IAggregationL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
