//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseAssosiationClass {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseAssosiationClass custom)

  // *** End programmer edit section *** (IBaseAssosiationClass custom)
}

export interface IAssosiationE extends IBaseAssosiationClass {
  assosiationName: string;
  // *** Start programmer edit section *** (IAssosiationE custom)

  // *** End programmer edit section *** (IAssosiationE custom)
}

export interface IAssosiationL extends IBaseAssosiationClass {
  assosiationName: string;
  // *** Start programmer edit section *** (IAssosiationL custom)

  // *** End programmer edit section *** (IAssosiationL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
