//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { ClassEnum } from '../enums/ClassEnum.types';
import { IAggregationD as IAggregationClassAggregationD } from './AggregationClass.types';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export interface IBaseClassTest {
  id: NonEmptyString;
  // *** Start programmer edit section *** (IBaseClassTest custom)

  // *** End programmer edit section *** (IBaseClassTest custom)
}

export interface IClassTestE extends IBaseClassTest {
  address: string;
  name: ClassEnum;
  assosiationClassId: NonEmptyString;
  aggregationClass: IAggregationClassAggregationD[];
  // *** Start programmer edit section *** (IClassTestE custom)

  // *** End programmer edit section *** (IClassTestE custom)
}

export interface IClassTestL extends IBaseClassTest {
  address: string;
  name: ClassEnum;
  // *** Start programmer edit section *** (IClassTestL custom)

  // *** End programmer edit section *** (IClassTestL custom)
}

// *** Start programmer edit section *** (Custom interfaces)

// *** End programmer edit section *** (Custom interfaces)
