//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Testt.ApplicationLayer.DTO.ClassTest
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using ICSSoft.STORMNET;
    using Testt;
    using Testt.ApplicationLayer;
    using Testt.ApplicationLayer.Attributes;
    using Testt.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления ClassTest.ClassTestE.
    /// </summary>
    [DataView(typeof(ClassTest), "ClassTestE")]
    public partial class ClassTestEDto : ClassTestDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ClassTestEDto"/>.
        /// </summary>
        public ClassTestEDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ClassTestEDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public ClassTestEDto(ClassTest source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Address.
        /// </summary>
        [PropertyName("Address")]
        [CaptionProperty("Address")]
        public string Address { get; set; } = string.Empty;

        /// <summary>
        /// Name.
        /// </summary>
        [PropertyName("Name")]
        [CaptionProperty("Name")]
        public ClassEnum Name { get; set; }

        /// <summary>
        /// AssosiationClass.
        /// </summary>
        [PropertyName("AssosiationClass")]
        [CaptionProperty("AssosiationClass")]
        public Guid AssosiationClassId { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// AggregationClass.
        /// </summary>
        public List<DTO.AggregationClass.AggregationDDto> AggregationClass { get; set; } = new List<DTO.AggregationClass.AggregationDDto>();

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override ClassTestEDto FillFromClass(ClassTest source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Address = source.Address;
            Name = source.Name;
            AssosiationClassId = PKHelper.GetGuidByObject(source.AssosiationClass).GetValueOrDefault();
            AggregationClass = source.AggregationClass.GetAllObjects().Cast<AggregationClass>().Select(d => new DTO.AggregationClass.AggregationDDto(d)).ToList();

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(ClassTest destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Address = Address;
            destination.Name = Name;

            if (AssosiationClassId != Guid.Empty)
            {
                AssosiationClass assosiationClass = new AssosiationClass();
                assosiationClass.SetExistObjectPrimaryKey(AssosiationClassId);
                destination.AssosiationClass = assosiationClass;
            }
            else
            {
                destination.AssosiationClass = null;
            }

            DataObject[] detailsAggregationClass = destination.AggregationClass.GetAllObjects();
            foreach (DTO.AggregationClass.AggregationDDto detailDto in AggregationClass)
            {
                DataObject? detail = detailsAggregationClass.FirstOrDefault(l => PKHelper.EQPK(l, detailDto.Id));
                if (detail == null)
                {
                    detail = new AggregationClass() { ClassTest = destination };
                    destination.AggregationClass.AddObject(detail);
                }

                detailDto.UpdateFromDto((AggregationClass)detail);
            }

            foreach (AggregationClass detail in detailsAggregationClass)
            {
                if (!AggregationClass.Any(a => PKHelper.EQPK(detail, a.Id)))
                {
                    detail.SetStatus(ObjectStatus.Deleted);
                }
            }

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
