//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Testt.ApplicationLayer.DTO.ClassTest
{
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using Testt;
    using Testt.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для фильтрации ClassTestL.
    /// </summary>
    public partial class ClassTestLFilterDto : FilterDtoBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ClassTestLFilterDto"/> class.
        /// </summary>
        public ClassTestLFilterDto()
        {
            DtoType = typeof(ClassTestLDto);
        }

        /// <summary>
        /// Address.
        /// </summary>
        public string? Address { get; set; }

        /// <summary>
        /// Address.
        /// </summary>
        public FilterOperation? AddressOp { get; set; }
        /// <summary>
        /// Name.
        /// </summary>
        public ClassEnum? Name { get; set; }

        /// <summary>
        /// Name.
        /// </summary>
        public FilterOperation? NameOp { get; set; }
        // *** Start programmer edit section *** (Custom filter props)

        // *** End programmer edit section *** (Custom filter props)

        /// <inheritdoc/>
        protected override Function? BuildFiltersFunction()
        {
            List<Function> limitFunctions = new List<Function>();

            // *** Start programmer edit section *** (Custom filters start)

            // *** End programmer edit section *** (Custom filters start)


            if (AddressOp != null)
            {
                limitFunctions.Add(GetFilterFunction<ClassTest>(AddressOp.Value, d => d.Address, Address));
            }

            if (NameOp != null)
            {
                limitFunctions.Add(GetFilterFunction<ClassTest>(NameOp.Value, d => d.Name, Name));
            }

            // *** Start programmer edit section *** (Custom filters end)

            // *** End programmer edit section *** (Custom filters end)

            if (limitFunctions.Count > 1)
            {
                return FunctionBuilder.BuildAnd(limitFunctions);
            }

            if (limitFunctions.Count == 1)
            {
                return limitFunctions[0];
            }

            return null;
        }
    }
}
