//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Testt.ApplicationLayer.DTO.ClassTest
{
    using System;
    using ICSSoft.STORMNET;
    using Testt;
    using Testt.ApplicationLayer;
    using Testt.ApplicationLayer.Attributes;
    using Testt.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления ClassTest.ClassTestL.
    /// </summary>
    [DataView(typeof(ClassTest), "ClassTestL")]
    public partial class ClassTestLDto : ClassTestDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ClassTestLDto"/>.
        /// </summary>
        public ClassTestLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ClassTestLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public ClassTestLDto(ClassTest source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// Address.
        /// </summary>
        [PropertyName("Address")]
        [CaptionProperty("Address")]
        public string Address { get; set; } = string.Empty;

        /// <summary>
        /// Name.
        /// </summary>
        [PropertyName("Name")]
        [CaptionProperty("Name")]
        public ClassEnum Name { get; set; }

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override ClassTestLDto FillFromClass(ClassTest source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            Address = source.Address;
            Name = source.Name;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(ClassTest destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.Address = Address;
            destination.Name = Name;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
