//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseAggregationClass } from '@/types/AggregationClass.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const AggregationClassService = {
  async GetAllAggregationClass(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/aggregationclass/${viewName}${queryStr}`);
  },

  async GetAggregationClass(id: string, viewName: string) {
    return await axiosInstance.get(`/aggregationclass/${viewName}/${id}`);
  },

  async CreateAggregationClass<T extends IBaseAggregationClass>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/aggregationclass/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateAggregationClass<T extends IBaseAggregationClass>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/aggregationclass/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteAggregationClass(id: string) {
    return await axiosInstance.delete(`/aggregationclass/${id}`);
  },

  async DeleteAllAggregationClass(ids: string[]) {
    return await axiosInstance.post(`/aggregationclass/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/aggregationclass/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
