//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseBusinessClass } from '@/types/BusinessClass.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const BusinessClassService = {
  async GetAllBusinessClass(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/businessclass/${viewName}${queryStr}`);
  },

  async GetBusinessClass(id: string, viewName: string) {
    return await axiosInstance.get(`/businessclass/${viewName}/${id}`);
  },

  async CreateBusinessClass<T extends IBaseBusinessClass>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/businessclass/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateBusinessClass<T extends IBaseBusinessClass>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/businessclass/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteBusinessClass(id: string) {
    return await axiosInstance.delete(`/businessclass/${id}`);
  },

  async DeleteAllBusinessClass(ids: string[]) {
    return await axiosInstance.post(`/businessclass/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/businessclass/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
