//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { DataTableFilterMeta, DataTableSortMeta } from 'primereact/datatable';

import axiosInstance from '@/api/instance';
import { IBaseClassTest } from '@/types/ClassTest.types';
import { getQueryString } from '@/utils/queryStringConverter';
import { SearchColumnsParam } from '@/types/helpers/SearchColumnsParam';

// *** Start programmer edit section *** (Import statements)

// *** End programmer edit section *** (Import statements)

export const ClassTestService = {
  async GetAllClassTest(
    viewName: string,
    perPage?: number,
    page?: number,
    sorting?: DataTableSortMeta[],
    filter?: DataTableFilterMeta,
    search?: SearchColumnsParam
  ) {
    const queryStr = getQueryString(perPage, page, sorting, filter, search);
    return await axiosInstance.get(`/classtest/${viewName}${queryStr}`);
  },

  async GetClassTest(id: string, viewName: string) {
    return await axiosInstance.get(`/classtest/${viewName}/${id}`);
  },

  async CreateClassTest<T extends IBaseClassTest>(data: T, viewName: string) {
    const response = await axiosInstance.post(`/classtest/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async UpdateClassTest<T extends IBaseClassTest>(data: T, viewName: string) {
    const response = await axiosInstance.put(`/classtest/${viewName}`, data, {
      headers: {
        'Content-Type': 'application/json',
      },
    });

    return response;
  },

  async DeleteClassTest(id: string) {
    return await axiosInstance.delete(`/classtest/${id}`);
  },

  async DeleteAllClassTest(ids: string[]) {
    return await axiosInstance.post(`/classtest/DeleteAll`, ids, {
      headers: {
        'Content-Type': 'application/json',
      },
    });
  },

  async GetCount(viewName: string) {
    return await axiosInstance.get(`/classtest/${viewName}/count`);
  },

  // *** Start programmer edit section *** (Custom methods)

  // *** End programmer edit section *** (Custom methods)
};
