//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Testt
{


    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// BusinessClassBS.
    /// </summary>
    // *** Start programmer edit section *** (BusinessClassBS CustomAttributes)

    // *** End programmer edit section *** (BusinessClassBS CustomAttributes)
    [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
    public class BusinessClassBS : ICSSoft.STORMNET.Business.BusinessServer
    {

        // *** Start programmer edit section *** (BusinessClassBS CustomMembers)

        // *** End programmer edit section *** (BusinessClassBS CustomMembers)

        // *** Start programmer edit section *** (OnUpdateBusinessClass CustomAttributes)

        // *** End programmer edit section *** (OnUpdateBusinessClass CustomAttributes)
        public virtual ICSSoft.STORMNET.DataObject[] OnUpdateBusinessClass(Testt.BusinessClass UpdatedObject)
        {
            // *** Start programmer edit section *** (OnUpdateBusinessClass)

            return new ICSSoft.STORMNET.DataObject[0];
            // *** End programmer edit section *** (OnUpdateBusinessClass)
        }
    }
}
