//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Testt.ApplicationLayer.DTO.AggregationClass
{
    using System;
    using ICSSoft.STORMNET;
    using Testt;
    using Testt.ApplicationLayer;
    using Testt.ApplicationLayer.Attributes;
    using Testt.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для представления AggregationClass.AggregationL.
    /// </summary>
    [DataView(typeof(AggregationClass), "AggregationL")]
    public partial class AggregationLDto : AggregationClassDtoBase
    {
        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AggregationLDto"/>.
        /// </summary>
        public AggregationLDto()
        {
        }

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AggregationLDto"/>.
        /// </summary>
        /// <param name="source">Объект для заполнения значений.</param>
        public AggregationLDto(AggregationClass source)
        {
            FillFromClass(source);
        }

                /// <summary>
        /// AggregationAtr.
        /// </summary>
        [PropertyName("AggregationAtr")]
        [CaptionProperty("AggregationAtr")]
        public string AggregationAtr { get; set; } = string.Empty;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        // *** Start programmer edit section *** (Custom details)

        // *** End programmer edit section *** (Custom details)

        /// <inheritdoc/>
        public override AggregationLDto FillFromClass(AggregationClass source)
        {
            if (source == null)
            {
                throw new ArgumentNullException(nameof(source));
            }

            Id = PKHelper.GetGuidByObject(source).GetValueOrDefault();
            AggregationAtr = source.AggregationAtr;

            // *** Start programmer edit section *** (FillFromClass custom)

            // *** End programmer edit section *** (FillFromClass custom)

            return this;
        }

        /// <inheritdoc/>
        public override void UpdateFromDto(AggregationClass destination)
        {
            if (destination == null)
            {
                throw new ArgumentNullException(nameof(destination));
            }

            destination.__PrimaryKey = Id;
            destination.AggregationAtr = AggregationAtr;

            // *** Start programmer edit section *** (UpdateFromDto custom)

            // *** End programmer edit section *** (UpdateFromDto custom)
        }
    }
}
