//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Testt.ApplicationLayer.DTO.AggregationClass
{
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using Testt;
    using Testt.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для фильтрации AggregationClassL.
    /// </summary>
    public partial class AggregationClassLFilterDto : FilterDtoBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AggregationClassLFilterDto"/> class.
        /// </summary>
        public AggregationClassLFilterDto()
        {
            DtoType = typeof(AggregationLDto);
        }

        /// <summary>
        /// AggregationAtr.
        /// </summary>
        public string? AggregationAtr { get; set; }

        /// <summary>
        /// AggregationAtr.
        /// </summary>
        public FilterOperation? AggregationAtrOp { get; set; }
        // *** Start programmer edit section *** (Custom filter props)

        // *** End programmer edit section *** (Custom filter props)

        /// <inheritdoc/>
        protected override Function? BuildFiltersFunction()
        {
            List<Function> limitFunctions = new List<Function>();

            // *** Start programmer edit section *** (Custom filters start)

            // *** End programmer edit section *** (Custom filters start)


            if (AggregationAtrOp != null)
            {
                limitFunctions.Add(GetFilterFunction<AggregationClass>(AggregationAtrOp.Value, d => d.AggregationAtr, AggregationAtr));
            }

            // *** Start programmer edit section *** (Custom filters end)

            // *** End programmer edit section *** (Custom filters end)

            if (limitFunctions.Count > 1)
            {
                return FunctionBuilder.BuildAnd(limitFunctions);
            }

            if (limitFunctions.Count == 1)
            {
                return limitFunctions[0];
            }

            return null;
        }
    }
}
