//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
export enum tView {
  AggregationD = 'AggregationD',
  AggregationE = 'AggregationE',
  AggregationL = 'AggregationL',
  AssosiationE = 'AssosiationE',
  AssosiationL = 'AssosiationL',
  ClassTestE = 'ClassTestE',
  ClassTestL = 'ClassTestL',
  // *** Start programmer edit section *** (Additional views)

  // *** End programmer edit section *** (Additional views)
}
