//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AggregationClassService } from '@/services/AggregationClass.service';
import { IBaseAggregationClass } from '@/types/AggregationClass.types';

const useCreateAggregationClass = <T extends IBaseAggregationClass>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type CreateRecordArgs = {
    aggregationClass: T;
    viewName: string;
  };

  const {
    mutate: createAggregationClass,
    mutateAsync: createAggregationClassAsync,
    isPending,
  } = useMutation({
    mutationFn: (createRecordArgs: CreateRecordArgs) =>
      AggregationClassService.CreateAggregationClass<T>(createRecordArgs.aggregationClass, createRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'aggregationClass';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { createAggregationClass, createAggregationClassAsync, isPending };
};

export default useCreateAggregationClass;
