//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AggregationClassService } from '@/services/AggregationClass.service';

const useDeleteAllAggregationClass = (
  onSuccess: (result: string[]) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteAllAggregationClass,
    mutateAsync: deleteAllAggregationClassAsync,
    isPending,
  } = useMutation({
    mutationFn: (ids: string[]) => AggregationClassService.DeleteAllAggregationClass(ids),
    onSuccess: (_, ids) => {
      const className = 'aggregationClass';
      ids.forEach((id) => {
        queryClient.removeQueries({ queryKey: [className, id] });
      });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(ids);
    },
    onError: (e) => onError(e),
  });

  return { deleteAllAggregationClass, deleteAllAggregationClassAsync, isPending };
};

export default useDeleteAllAggregationClass;
