//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AggregationClassService } from '@/services/AggregationClass.service';

const useDeleteAggregationClass = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteAggregationClass,
    mutateAsync: deleteAggregationClassAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => AggregationClassService.DeleteAggregationClass(id),
    onSuccess: (_, id) => {
      const className = 'aggregationClass';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteAggregationClass, deleteAggregationClassAsync, isPending };
};

export default useDeleteAggregationClass;
