//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { AggregationClassService } from '@/services/AggregationClass.service';
import { IBaseAggregationClass } from '@/types/AggregationClass.types';

const useUpdateAggregationClass = <T extends IBaseAggregationClass>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type UpdateRecordArgs = {
    aggregationClass: T;
    viewName: string;
  };

  const {
    mutate: updateAggregationClass,
    mutateAsync: updateAggregationClassAsync,
    isPending,
  } = useMutation({
    mutationFn: (updateRecordArgs: UpdateRecordArgs) =>
      AggregationClassService.UpdateAggregationClass<T>(updateRecordArgs.aggregationClass, updateRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'aggregationClass';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { updateAggregationClass, updateAggregationClassAsync, isPending };
};

export default useUpdateAggregationClass;
