//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { BusinessClassService } from '@/services/BusinessClass.service';

const useDeleteBusinessClass = (onSuccess: (result: string) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteBusinessClass,
    mutateAsync: deleteBusinessClassAsync,
    isPending,
  } = useMutation({
    mutationFn: (id: string) => BusinessClassService.DeleteBusinessClass(id),
    onSuccess: (_, id) => {
      const className = 'businessClass';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(id);
    },
    onError: (e) => onError(e),
  });

  return { deleteBusinessClass, deleteBusinessClassAsync, isPending };
};

export default useDeleteBusinessClass;
