//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { BusinessClassService } from '@/services/BusinessClass.service';
import { IBaseBusinessClass } from '@/types/BusinessClass.types';

const useUpdateBusinessClass = <T extends IBaseBusinessClass>(
  onSuccess: (result: T) => void,
  onError: (e: Error | AxiosError) => void
) => {
  const queryClient = useQueryClient();

  type UpdateRecordArgs = {
    businessClass: T;
    viewName: string;
  };

  const {
    mutate: updateBusinessClass,
    mutateAsync: updateBusinessClassAsync,
    isPending,
  } = useMutation({
    mutationFn: (updateRecordArgs: UpdateRecordArgs) =>
      BusinessClassService.UpdateBusinessClass<T>(updateRecordArgs.businessClass, updateRecordArgs.viewName),
    onSuccess: (response, variables) => {
      const id = response.data.id;
      const { viewName } = variables;
      const className = 'businessClass';
      queryClient.invalidateQueries({ queryKey: [className, id] });
      queryClient.invalidateQueries({ queryKey: [className, 'list', viewName] });
      onSuccess(response.data);
    },
    onError: (e) => onError(e),
  });

  return { updateBusinessClass, updateBusinessClassAsync, isPending };
};

export default useUpdateBusinessClass;
