//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Testt.ApplicationLayer.Services
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Reflection;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using ICSSoft.STORMNET.Business;
    using ICSSoft.STORMNET.Exceptions;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using Testt;
    using Testt.ApplicationLayer.Attributes;
    using Testt.ApplicationLayer.DTO;
    using Testt.ApplicationLayer.DTO.ClassTest;
    using Testt.ApplicationLayer.Helpers;
    using Testt.ApplicationLayer.Mapping;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Сервис для работы с <see cref="ClassTest"/>.
    /// </summary>
    public partial class ClassTestService : IClassTestService
    {
        private readonly IDataService _dataService;
        private readonly ServiceHelper _serviceHelper;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ClassTestService"/>.
        /// </summary>
        /// <param name="dataService">Сервис доступа к данным.</param>
        /// <param name="serviceHelper">Инструменты для сервисов.</param>
        public ClassTestService(IDataService dataService, ServiceHelper serviceHelper)
        {
            _dataService = dataService;
            _serviceHelper = serviceHelper;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <inheritdoc/>
        public async Task<LoadingCustomizationStruct> BuildLcs<TDto>(int? perPage = null, int? page = null, string[]? sorting = null, FilterDtoBase? filter = null)
            where TDto : ClassTestDtoBase, new()
        {
            View currentView = DataViewAttribute.GetView<TDto>();

            LoadingCustomizationStruct lcs = LoadingCustomizationStruct.GetSimpleStruct(typeof(ClassTest), currentView);

            List<ColumnsSortDef> sortDefs = new List<ColumnsSortDef>();
            if (sorting != null && sorting.Length > 0)
            {
                Type dtoType = typeof(TDto);
                foreach (string sort in sorting)
                {
                    SortOrder order = sort.StartsWith('-') ? SortOrder.Desc : SortOrder.Asc;
                    string propName = order == SortOrder.Desc ? sort[1..] : sort;
                    string? realPropName = dtoType.GetProperty(propName)?.GetCustomAttribute<PropertyNameAttribute>()?.PropName;
                    sortDefs.Add(new ColumnsSortDef(realPropName ?? propName, order));
                }
            }
            else
            {
                sortDefs.Add(new ColumnsSortDef("__PrimaryKey", SortOrder.Asc));
            }

            lcs.ColumnsSort = sortDefs.ToArray();

            if (perPage.HasValue && page.HasValue)
            {
                lcs.RowNumber = new RowNumberDef((page.Value * perPage.Value) + 1, (page.Value + 1) * perPage.Value);
            }

            Function? limit = await GetLimitFunction(filter);
            if (limit != null)
            {
                lcs.LimitFunction = limit;
            }

            // *** Start programmer edit section *** (ClassTestService BuildLcs)

            // *** End programmer edit section *** (ClassTestService BuildLcs)

            return lcs;
        }

        /// <inheritdoc/>
        public async Task<IEnumerable<TDto>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase? filter = null)
            where TDto : ClassTestDtoBase, new()
        {
            // *** Start programmer edit section *** (GetAll view tuning)

            // *** End programmer edit section *** (GetAll view tuning)

            LoadingCustomizationStruct lcs = await BuildLcs<TDto>(perPage, page, sorting, filter);

            // *** Start programmer edit section *** (GetAll before load)

            // *** End programmer edit section *** (GetAll before load)

            DataObject[] dataObjects = _dataService.LoadObjects(lcs);

            // *** Start programmer edit section *** (GetAll after load)

            // *** End programmer edit section *** (GetAll after load)

            return dataObjects
                .OfType<ClassTest>()
                .Select(x => x.MapToDto<TDto>())
                .ToList();
        }

        /// <inheritdoc/>
        public async Task<TDto> GetById<TDto>(Guid id)
            where TDto : ClassTestDtoBase, new()
        {
            ClassTest entity = await LoadExisting(id, DataViewAttribute.GetView<TDto>());
            return entity.MapToDto<TDto>();
        }

        /// <inheritdoc/>
        public async Task<TDto?> GetOrDefaultById<TDto>(Guid id)
            where TDto : ClassTestDtoBase, new()
        {
            ClassTest? entity = await LoadNullable(id, DataViewAttribute.GetView<TDto>());
            return entity?.MapToDto<TDto>();
        }

        /// <inheritdoc/>
        public async Task<int> Count<TDto>(FilterDtoBase? filter = null)
            where TDto : ClassTestDtoBase, new()
        {
            View currentView = DataViewAttribute.GetView<TDto>();

            // *** Start programmer edit section *** (Count view tuning)

            // *** End programmer edit section *** (Count view tuning)

            LoadingCustomizationStruct lcs = LoadingCustomizationStruct.GetSimpleStruct(typeof(ClassTest), currentView);

            Function? limit = await GetLimitFunction(filter);
            if (limit != null)
            {
                lcs.LimitFunction = limit;
            }

            // *** Start programmer edit section *** (Count before load)

            // *** End programmer edit section *** (Count before load)

            return _dataService.GetObjectsCount(lcs);
        }

        /// <inheritdoc/>
        public async Task<ClassTest> Create(ClassTestEDto dto)
        {
            if (dto == null)
            {
                LogService.LogError("Не передано DTO при создании ClassTest.");
                throw new ArgumentNullException(nameof(dto));
            }

            if (dto.Id == Guid.Empty)
            {
                LogService.LogError("Id не может быть пустым при создании ClassTest.");
                throw new ArgumentException("Id не может быть пустым при создании ClassTest.");
            }

            // *** Start programmer edit section *** (ClassTestE before create validation)

            // *** End programmer edit section *** (ClassTestE before create validation)

            ClassTest entity = new ClassTest();
            entity.UpdateFromDto(dto);

            List<DataObject> updatedObjects = new () { entity };

            // *** Start programmer edit section *** (ClassTestE before create)

            // *** End programmer edit section *** (ClassTestE before create)

            try
            {
                if (updatedObjects.Count == 1)
                {
                    _dataService.UpdateObject(updatedObjects[0]);
                }
                else
                {
                    DataObject[] upd = updatedObjects.ToArray();
                    _dataService.UpdateObjects(ref upd);
                }
            }
            catch (Exception ex)
            {
                LogService.LogError("Произошла ошибка при создании ClassTest.", ex);
                throw new Exception($"Произошла ошибка при создании ClassTest. {ex.Message}");
            }

            return await LoadExisting(dto.Id, DataViewAttribute.GetView<ClassTestEDto>());
        }

        /// <inheritdoc/>
        public async Task<ClassTest> Update(ClassTestEDto dto)
        {
            if (dto == null)
            {
                LogService.LogError("Не передано DTO для обновления ClassTest.");
                throw new ArgumentNullException(nameof(dto));
            }

            // *** Start programmer edit section *** (ClassTestE before update validation)

            // *** End programmer edit section *** (ClassTestE before update validation)

            ClassTest entity = await LoadExisting(dto.Id, DataViewAttribute.GetView<ClassTestEDto>());
            entity.UpdateFromDto(dto);

            List<DataObject> updatedObjects = new () { entity };

            // *** Start programmer edit section *** (ClassTestE before update)

            // *** End programmer edit section *** (ClassTestE before update)

            try
            {
                if (updatedObjects.Count == 1)
                {
                    _dataService.UpdateObject(updatedObjects[0]);
                }
                else
                {
                    DataObject[] upd = updatedObjects.ToArray();
                    _dataService.UpdateObjects(ref upd);
                }
            }
            catch (Exception ex)
            {
                LogService.LogError($"Произошла ошибка при обновлении ClassTest с Id {dto.Id}.", ex);
                throw new Exception($"Произошла ошибка при обновлении ClassTest. {ex.Message}");
            }

            return await LoadExisting(dto.Id, DataViewAttribute.GetView<ClassTestEDto>());
        }

        /// <summary>
        /// Получить список удаляемых объектов, в том числе связанных объектов, которые нужно удалить вместе с основным.
        /// Например детейлы, исторические данные и т.п.
        /// </summary>
        /// <param name="id">ID объекта.</param>
        /// <returns>Список удаляемых объектов.</returns>
        private async Task<DataObject[]> GetObjectsForDelete(Guid id)
        {
            // *** Start programmer edit section *** (objects for delete validation)

            // *** End programmer edit section *** (objects for delete validation)

            ClassTest entity = await LoadExisting(id);
            List<DataObject> listForDelete = new List<DataObject>() { entity };

            // *** Start programmer edit section *** (objects for delete)

            // *** End programmer edit section *** (objects for delete)

            entity.SetStatus(ObjectStatus.Deleted);

            return listForDelete.ToArray();
        }

        /// <inheritdoc/>
        public async Task<bool> Delete(Guid id)
        {
            DataObject[] dataObjectsForDelete = await GetObjectsForDelete(id);
            _dataService.UpdateObjects(ref dataObjectsForDelete);

            return true;
        }

        /// <inheritdoc/>
        public async Task<bool> DeleteAll(List<Guid> ids)
        {
            if (ids == null)
            {
                throw new ArgumentException($"Не указан параметр", nameof(ids));
            }

            List<DataObject> listObjectsForDelete = new ();

            foreach (Guid id in ids)
            {
                listObjectsForDelete.AddRange(await GetObjectsForDelete(id));
            }

            if (listObjectsForDelete.Any())
            {
                DataObject[] dataObjectsForDelete = listObjectsForDelete.ToArray();
                _dataService.UpdateObjects(ref dataObjectsForDelete);
            }

            return true;
        }

        /// <summary>
        /// Получить функцию ограничения из фильтра.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Функция ограничения.</returns>
        private async Task<Function?> GetLimitFunction(FilterDtoBase? filter)
        {
            // *** Start programmer edit section *** (GetLimitFunction custom)

            // *** End programmer edit section *** (GetLimitFunction custom)

            if (filter != null)
            {
                return filter.GetLimitFunction();
            }

            return null;
        }

        /// <summary>
        /// Загружает существующий объект или генерирует исключение, если он не найден или удалён.
        /// </summary>
        /// <param name="id">Идентификатор объекта.</param>
        /// <param name="view">Необязательное представление данных.</param>
        /// <returns>Загруженный объект <see cref="ClassTest"/>.</returns>
        private async Task<ClassTest> LoadExisting(Guid id, View? view = null)
        {
            if (id == Guid.Empty)
            {
                throw new ArgumentException("Id не может быть пустым.", nameof(id));
            }

            ClassTest entity = new ClassTest();
            entity.SetExistObjectPrimaryKey(id);

            try
            {
                if (view == null)
                {
                    _dataService.LoadObject(entity);
                }
                else
                {
                    // *** Start programmer edit section *** (LoadExisting before view load)

                    // *** End programmer edit section *** (LoadExisting before view load)

                    _dataService.LoadObject(view, entity);
                }
            }
            catch (CantFindDataObjectException)
            {
                throw new KeyNotFoundException($"ClassTest с Id={id} не найден.");
            }

            if (entity.GetStatus() == ObjectStatus.Deleted)
            {
                throw new InvalidOperationException($"ClassTest с Id={id} уже удалён.");
            }

            return entity;
        }

        /// <summary>
        /// Загружает существующий объект или null, если он не найден или удалён.
        /// </summary>
        /// <param name="id">Идентификатор объекта.</param>
        /// <param name="view">Необязательное представление данных.</param>
        /// <returns>Загруженный объект <see cref="ClassTest"/>.</returns>
        private async Task<ClassTest?> LoadNullable(Guid id, View? view = null)
        {
            if (id == Guid.Empty)
            {
                throw new ArgumentException("Id не может быть пустым.", nameof(id));
            }

            ClassTest entity = new ClassTest();
            entity.SetExistObjectPrimaryKey(id);

            try
            {
                if (view == null)
                {
                    _dataService.LoadObject(entity);
                }
                else
                {
                    // *** Start programmer edit section *** (LoadNullable before view load)

                    // *** End programmer edit section *** (LoadNullable before view load)

                    _dataService.LoadObject(view, entity);
                }
            }
            catch (CantFindDataObjectException)
            {
                return null;
            }

            if (entity.GetStatus() == ObjectStatus.Deleted)
            {
                return null;
            }

            return entity;
        }
    }
}
