//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Testt.ApplicationLayer.DTO.AssosiationClass
{
    using System;
    using System.Collections.Generic;
    using ICSSoft.STORMNET.FunctionalLanguage;
    using Testt;
    using Testt.ApplicationLayer.Helpers;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// DTO для фильтрации AssosiationClassL.
    /// </summary>
    public partial class AssosiationClassLFilterDto : FilterDtoBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AssosiationClassLFilterDto"/> class.
        /// </summary>
        public AssosiationClassLFilterDto()
        {
            DtoType = typeof(AssosiationLDto);
        }

        /// <summary>
        /// AssosiationName.
        /// </summary>
        public string? AssosiationName { get; set; }

        /// <summary>
        /// AssosiationName.
        /// </summary>
        public FilterOperation? AssosiationNameOp { get; set; }
        // *** Start programmer edit section *** (Custom filter props)

        // *** End programmer edit section *** (Custom filter props)

        /// <inheritdoc/>
        protected override Function? BuildFiltersFunction()
        {
            List<Function> limitFunctions = new List<Function>();

            // *** Start programmer edit section *** (Custom filters start)

            // *** End programmer edit section *** (Custom filters start)


            if (AssosiationNameOp != null)
            {
                limitFunctions.Add(GetFilterFunction<AssosiationClass>(AssosiationNameOp.Value, d => d.AssosiationName, AssosiationName));
            }

            // *** Start programmer edit section *** (Custom filters end)

            // *** End programmer edit section *** (Custom filters end)

            if (limitFunctions.Count > 1)
            {
                return FunctionBuilder.BuildAnd(limitFunctions);
            }

            if (limitFunctions.Count == 1)
            {
                return limitFunctions[0];
            }

            return null;
        }
    }
}
