//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { AxiosError } from 'axios';

import { ClassTestService } from '@/services/ClassTest.service';

const useDeleteAllClassTest = (onSuccess: (result: string[]) => void, onError: (e: Error | AxiosError) => void) => {
  const queryClient = useQueryClient();

  const {
    mutate: deleteAllClassTest,
    mutateAsync: deleteAllClassTestAsync,
    isPending,
  } = useMutation({
    mutationFn: (ids: string[]) => ClassTestService.DeleteAllClassTest(ids),
    onSuccess: (_, ids) => {
      const className = 'classTest';
      ids.forEach((id) => {
        queryClient.removeQueries({ queryKey: [className, id] });
      });
      queryClient.invalidateQueries({ queryKey: [className, 'list'] });
      queryClient.invalidateQueries({ queryKey: [className, 'count'] });
      onSuccess(ids);
    },
    onError: (e) => onError(e),
  });

  return { deleteAllClassTest, deleteAllClassTestAsync, isPending };
};

export default useDeleteAllClassTest;
