//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Testt.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Testt;
    using Testt.ApplicationLayer.DTO;
    using Testt.ApplicationLayer.DTO.AggregationClass;
    using Testt.ApplicationLayer.Helpers;
    using Testt.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для AggregationClass.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class AggregationClassController : ControllerBase
    {
        private readonly IAggregationClassService _aggregationClassService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AggregationClassController"/>.
        /// </summary>
        /// <param name="aggregationClassService">Сервис для работы с AggregationClass.</param>
        public AggregationClassController(IAggregationClassService aggregationClassService)
        {
            _aggregationClassService = aggregationClassService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех AggregationClass в форме AggregationDDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("AggregationD")]
        public async Task<ActionResult<GetAllRequestResult<AggregationDDto>>> GetAllAggregationD(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<AggregationDDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить AggregationClass по идентификатору в форме AggregationDDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="AggregationDDto"/>, если найден.</returns>
        [HttpGet("AggregationD/{id:guid}")]
        public async Task<ActionResult<AggregationDDto>> GetByIdAggregationD(Guid id)
        {
            return await GetById<AggregationDDto>(id);
        }

        /// <summary>
        /// Получить общее количество AggregationClass.
        /// </summary>
        /// <returns>Количество AggregationClass.</returns>
        [HttpGet("AggregationD/count")]
        public async Task<ActionResult<int>> GetCountAggregationD()
        {
            return await GetCount<AggregationDDto>();
        }

        /// <summary>
        /// Получить список всех AggregationClass в форме AggregationEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("AggregationE")]
        public async Task<ActionResult<GetAllRequestResult<AggregationEDto>>> GetAllAggregationE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<AggregationEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить AggregationClass по идентификатору в форме AggregationEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="AggregationEDto"/>, если найден.</returns>
        [HttpGet("AggregationE/{id:guid}")]
        public async Task<ActionResult<AggregationEDto>> GetByIdAggregationE(Guid id)
        {
            return await GetById<AggregationEDto>(id);
        }

        /// <summary>
        /// Получить общее количество AggregationClass.
        /// </summary>
        /// <returns>Количество AggregationClass.</returns>
        [HttpGet("AggregationE/count")]
        public async Task<ActionResult<int>> GetCountAggregationE()
        {
            return await GetCount<AggregationEDto>();
        }

        /// <summary>
        /// Получить список всех AggregationClass в форме AggregationLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("AggregationL")]
        public async Task<ActionResult<GetAllRequestResult<AggregationLDto>>> GetAllAggregationL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<AggregationLDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить AggregationClass по идентификатору в форме AggregationLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="AggregationLDto"/>, если найден.</returns>
        [HttpGet("AggregationL/{id:guid}")]
        public async Task<ActionResult<AggregationLDto>> GetByIdAggregationL(Guid id)
        {
            return await GetById<AggregationLDto>(id);
        }

        /// <summary>
        /// Получить общее количество AggregationClass.
        /// </summary>
        /// <returns>Количество AggregationClass.</returns>
        [HttpGet("AggregationL/count")]
        public async Task<ActionResult<int>> GetCountAggregationL()
        {
            return await GetCount<AggregationLDto>();
        }

        /// <summary>
        /// Создать новый AggregationClass в форме AggregationEDto.
        /// </summary>
        /// <param name="dto">DTO с данными для создания.</param>
        /// <returns>Созданный <see cref="AggregationEDto"/>.</returns>
        [HttpPost("AggregationE")]
        public async Task<ActionResult<AggregationEDto>> CreateAggregationE([FromBody] AggregationEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                AggregationClass created = await _aggregationClassService.Create(dto);
                AggregationEDto createdDto = new AggregationEDto(created);

                return CreatedAtAction(nameof(GetByIdAggregationE), new { id = createdDto.Id }, createdDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при создании AggregationClass", ex);

                return BadRequest();
            }
        }

        /// <summary>
        /// Обновить или создать AggregationClass в форме AggregationEDto.
        /// </summary>
        /// <param name="dto">DTO с новыми данными.</param>
        /// <returns>Обновленный AggregationClass.</returns>
        [HttpPut("AggregationE")]
        public async Task<ActionResult<AggregationEDto>> UpdateAggregationE([FromBody] AggregationEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                AggregationEDto existed = await _aggregationClassService.GetOrDefaultById<AggregationEDto>(dto.Id);
                AggregationClass createdOrUpdated = new ();

                if (existed == null)
                {
                    createdOrUpdated = await _aggregationClassService.Create(dto);
                }
                else
                {
                    createdOrUpdated = await _aggregationClassService.Update(dto);
                }

                AggregationEDto updatedDto = new (createdOrUpdated);

                return Ok(updatedDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при обновлении AggregationClass", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить AggregationClass.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _aggregationClassService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении AggregationClass", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все AggregationClass для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _aggregationClassService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении AggregationClass", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех AggregationClass.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список AggregationClass.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : AggregationClassDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _aggregationClassService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _aggregationClassService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении AggregationClass", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить AggregationClass по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>AggregationClass в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : AggregationClassDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _aggregationClassService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении AggregationClass по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество AggregationClass.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество AggregationClass.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : AggregationClassDtoBase, new()
        {
            try
            {
                int result = await _aggregationClassService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва AggregationClass", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
