//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Testt.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Testt;
    using Testt.ApplicationLayer.DTO;
    using Testt.ApplicationLayer.DTO.AssosiationClass;
    using Testt.ApplicationLayer.Helpers;
    using Testt.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для AssosiationClass.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class AssosiationClassController : ControllerBase
    {
        private readonly IAssosiationClassService _assosiationClassService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="AssosiationClassController"/>.
        /// </summary>
        /// <param name="assosiationClassService">Сервис для работы с AssosiationClass.</param>
        public AssosiationClassController(IAssosiationClassService assosiationClassService)
        {
            _assosiationClassService = assosiationClassService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех AssosiationClass в форме AssosiationEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("AssosiationE")]
        public async Task<ActionResult<GetAllRequestResult<AssosiationEDto>>> GetAllAssosiationE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<AssosiationEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить AssosiationClass по идентификатору в форме AssosiationEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="AssosiationEDto"/>, если найден.</returns>
        [HttpGet("AssosiationE/{id:guid}")]
        public async Task<ActionResult<AssosiationEDto>> GetByIdAssosiationE(Guid id)
        {
            return await GetById<AssosiationEDto>(id);
        }

        /// <summary>
        /// Получить общее количество AssosiationClass.
        /// </summary>
        /// <returns>Количество AssosiationClass.</returns>
        [HttpGet("AssosiationE/count")]
        public async Task<ActionResult<int>> GetCountAssosiationE()
        {
            return await GetCount<AssosiationEDto>();
        }

        /// <summary>
        /// Получить список всех AssosiationClass в форме AssosiationLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("AssosiationL")]
        public async Task<ActionResult<GetAllRequestResult<AssosiationLDto>>> GetAllAssosiationL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<AssosiationLDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить AssosiationClass по идентификатору в форме AssosiationLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="AssosiationLDto"/>, если найден.</returns>
        [HttpGet("AssosiationL/{id:guid}")]
        public async Task<ActionResult<AssosiationLDto>> GetByIdAssosiationL(Guid id)
        {
            return await GetById<AssosiationLDto>(id);
        }

        /// <summary>
        /// Получить общее количество AssosiationClass.
        /// </summary>
        /// <returns>Количество AssosiationClass.</returns>
        [HttpGet("AssosiationL/count")]
        public async Task<ActionResult<int>> GetCountAssosiationL()
        {
            return await GetCount<AssosiationLDto>();
        }

        /// <summary>
        /// Создать новый AssosiationClass в форме AssosiationEDto.
        /// </summary>
        /// <param name="dto">DTO с данными для создания.</param>
        /// <returns>Созданный <see cref="AssosiationEDto"/>.</returns>
        [HttpPost("AssosiationE")]
        public async Task<ActionResult<AssosiationEDto>> CreateAssosiationE([FromBody] AssosiationEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                AssosiationClass created = await _assosiationClassService.Create(dto);
                AssosiationEDto createdDto = new AssosiationEDto(created);

                return CreatedAtAction(nameof(GetByIdAssosiationE), new { id = createdDto.Id }, createdDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при создании AssosiationClass", ex);

                return BadRequest();
            }
        }

        /// <summary>
        /// Обновить или создать AssosiationClass в форме AssosiationEDto.
        /// </summary>
        /// <param name="dto">DTO с новыми данными.</param>
        /// <returns>Обновленный AssosiationClass.</returns>
        [HttpPut("AssosiationE")]
        public async Task<ActionResult<AssosiationEDto>> UpdateAssosiationE([FromBody] AssosiationEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                AssosiationEDto existed = await _assosiationClassService.GetOrDefaultById<AssosiationEDto>(dto.Id);
                AssosiationClass createdOrUpdated = new ();

                if (existed == null)
                {
                    createdOrUpdated = await _assosiationClassService.Create(dto);
                }
                else
                {
                    createdOrUpdated = await _assosiationClassService.Update(dto);
                }

                AssosiationEDto updatedDto = new (createdOrUpdated);

                return Ok(updatedDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при обновлении AssosiationClass", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить AssosiationClass.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _assosiationClassService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении AssosiationClass", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все AssosiationClass для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _assosiationClassService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении AssosiationClass", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех AssosiationClass.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список AssosiationClass.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : AssosiationClassDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _assosiationClassService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _assosiationClassService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении AssosiationClass", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить AssosiationClass по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>AssosiationClass в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : AssosiationClassDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _assosiationClassService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении AssosiationClass по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество AssosiationClass.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество AssosiationClass.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : AssosiationClassDtoBase, new()
        {
            try
            {
                int result = await _assosiationClassService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва AssosiationClass", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
