//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file, except  programmer edit sections, will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Testt.WebAPI.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using ICSSoft.STORMNET;
    using Microsoft.AspNetCore.Mvc;
    using Testt;
    using Testt.ApplicationLayer.DTO;
    using Testt.ApplicationLayer.DTO.ClassTest;
    using Testt.ApplicationLayer.Helpers;
    using Testt.ApplicationLayer.Services;

    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)

    /// <summary>
    /// Контроллер для ClassTest.
    /// </summary>
    [ApiController]
    [Route("[controller]")]
    public partial class ClassTestController : ControllerBase
    {
        private readonly IClassTestService _classTestService;

        // *** Start programmer edit section *** (Custom properties)

        // *** End programmer edit section *** (Custom properties)

        /// <summary>
        /// Инициализирует новый экземпляр <see cref="ClassTestController"/>.
        /// </summary>
        /// <param name="classTestService">Сервис для работы с ClassTest.</param>
        public ClassTestController(IClassTestService classTestService)
        {
            _classTestService = classTestService;
        }

        // *** Start programmer edit section *** (Custom constructors)

        // *** End programmer edit section *** (Custom constructors)

        /// <summary>
        /// Получить список всех ClassTest в форме ClassTestEDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("ClassTestE")]
        public async Task<ActionResult<GetAllRequestResult<ClassTestEDto>>> GetAllClassTestE(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null)
        {
            return await GetAll<ClassTestEDto>(perPage, page, sorting);
        }

        /// <summary>
        /// Получить ClassTest по идентификатору в форме ClassTestEDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="ClassTestEDto"/>, если найден.</returns>
        [HttpGet("ClassTestE/{id:guid}")]
        public async Task<ActionResult<ClassTestEDto>> GetByIdClassTestE(Guid id)
        {
            return await GetById<ClassTestEDto>(id);
        }

        /// <summary>
        /// Получить общее количество ClassTest.
        /// </summary>
        /// <returns>Количество ClassTest.</returns>
        [HttpGet("ClassTestE/count")]
        public async Task<ActionResult<int>> GetCountClassTestE()
        {
            return await GetCount<ClassTestEDto>();
        }

        /// <summary>
        /// Получить список всех ClassTest в форме ClassTestLDto.
        /// </summary>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр.</param>
        /// <returns>Список объектов.</returns>
        [HttpGet("ClassTestL")]
        public async Task<ActionResult<GetAllRequestResult<ClassTestLDto>>> GetAllClassTestL(int? perPage = null, int? page = null, [FromQuery] string[] sorting = null, [FromQuery] ClassTestLFilterDto filter = null)
        {
            return await GetAll<ClassTestLDto>(perPage, page, sorting, filter);
        }

        /// <summary>
        /// Получить ClassTest по идентификатору в форме ClassTestLDto.
        /// </summary>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns><see cref="ClassTestLDto"/>, если найден.</returns>
        [HttpGet("ClassTestL/{id:guid}")]
        public async Task<ActionResult<ClassTestLDto>> GetByIdClassTestL(Guid id)
        {
            return await GetById<ClassTestLDto>(id);
        }

        /// <summary>
        /// Получить общее количество ClassTest.
        /// </summary>
        /// <returns>Количество ClassTest.</returns>
        [HttpGet("ClassTestL/count")]
        public async Task<ActionResult<int>> GetCountClassTestL()
        {
            return await GetCount<ClassTestLDto>();
        }

        /// <summary>
        /// Создать новый ClassTest в форме ClassTestEDto.
        /// </summary>
        /// <param name="dto">DTO с данными для создания.</param>
        /// <returns>Созданный <see cref="ClassTestEDto"/>.</returns>
        [HttpPost("ClassTestE")]
        public async Task<ActionResult<ClassTestEDto>> CreateClassTestE([FromBody] ClassTestEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                ClassTest created = await _classTestService.Create(dto);
                ClassTestEDto createdDto = new ClassTestEDto(created);

                return CreatedAtAction(nameof(GetByIdClassTestE), new { id = createdDto.Id }, createdDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при создании ClassTest", ex);

                return BadRequest();
            }
        }

        /// <summary>
        /// Обновить или создать ClassTest в форме ClassTestEDto.
        /// </summary>
        /// <param name="dto">DTO с новыми данными.</param>
        /// <returns>Обновленный ClassTest.</returns>
        [HttpPut("ClassTestE")]
        public async Task<ActionResult<ClassTestEDto>> UpdateClassTestE([FromBody] ClassTestEDto dto)
        {
            if (dto == null)
            {
                return BadRequest();
            }

            try
            {
                ClassTestEDto existed = await _classTestService.GetOrDefaultById<ClassTestEDto>(dto.Id);
                ClassTest createdOrUpdated = new ();

                if (existed == null)
                {
                    createdOrUpdated = await _classTestService.Create(dto);
                }
                else
                {
                    createdOrUpdated = await _classTestService.Update(dto);
                }

                ClassTestEDto updatedDto = new (createdOrUpdated);

                return Ok(updatedDto);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при обновлении ClassTest", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить ClassTest.
        /// </summary>
        /// <param name="id">GUID удаляемого объекта.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpDelete("{id:guid}")]
        public async Task<IActionResult> Delete(Guid id)
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                await _classTestService.Delete(id);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении ClassTest", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Удалить все ClassTest для переданных id.
        /// </summary>
        /// <param name="ids">GUIDы удаляемых объектов.</param>
        /// <returns>204 No Content, если успешно.</returns>
        [HttpPost("DeleteAll")]
        public async Task<IActionResult> DeleteAll([FromBody] List<Guid> ids)
        {
            if (ids == null || !ids.Any())
            {
                return BadRequest();
            }

            try
            {
                await _classTestService.DeleteAll(ids);

                return NoContent();
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при удалении ClassTest", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom public methods)

        // *** End programmer edit section *** (Custom public methods)

        /// <summary>
        /// Получить список всех ClassTest.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="perPage">Элементов на странице.</param>
        /// <param name="page">Текущая страница.</param>
        /// <param name="sorting">Сортировка.</param>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Список ClassTest.</returns>
        private async Task<ActionResult<GetAllRequestResult<TDto>>> GetAll<TDto>(int? perPage = null, int? page = null, string[] sorting = null, FilterDtoBase filter = null)
            where TDto : ClassTestDtoBase, new()
        {
            try
            {
                Task<IEnumerable<TDto>> getAllTask = _classTestService.GetAll<TDto>(perPage, page, sorting, filter);
                Task<int> countTask = _classTestService.Count<TDto>(filter);

                IEnumerable<TDto> data = await getAllTask;
                int count = await countTask;
                GetAllRequestResult<TDto> result = new GetAllRequestResult<TDto>() { Records = data, Count = count };

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении ClassTest", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить ClassTest по идентификатору.
        /// </summary>
        /// <typeparam name="TDto">Тип DTO.</typeparam>
        /// <param name="id">Уникальный идентификатор.</param>
        /// <returns>ClassTest в форме указанного DTO, если найден.</returns>
        private async Task<ActionResult<TDto>> GetById<TDto>(Guid id)
            where TDto : ClassTestDtoBase, new()
        {
            if (id == Guid.Empty)
            {
                return BadRequest();
            }

            try
            {
                TDto result = await _classTestService.GetById<TDto>(id);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (KeyNotFoundException)
            {
                return NotFound();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении ClassTest по id", ex);

                return BadRequest(ex.Message);
            }
        }

        /// <summary>
        /// Получить общее количество ClassTest.
        /// </summary>
        /// <param name="filter">Фильтр для вычитки.</param>
        /// <returns>Количество ClassTest.</returns>
        private async Task<ActionResult<int>> GetCount<TDto>(FilterDtoBase filter = null)
            where TDto : ClassTestDtoBase, new()
        {
            try
            {
                int result = await _classTestService.Count<TDto>(filter);

                return Ok(result);
            }
            catch (Exception ex) when (ex is ICSSoft.STORMNET.UnauthorizedAccessException or System.UnauthorizedAccessException)
            {
                return Forbid();
            }
            catch (Exception ex)
            {
                LogService.LogError("Ошибка при получении кол-ва ClassTest", ex);

                return BadRequest(ex.Message);
            }
        }

        // *** Start programmer edit section *** (Custom private methods)

        // *** End programmer edit section *** (Custom private methods)
    }
}
